[project]
name = "epidemic-simulator"
version = "0.1.0"
description = "City Scale Epidemic Simulator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.1",
    "geopy>=2.4.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "scipy>=1.16.2",
    "shapely>=2.1.2",
]
